default_platform(:ios)  

platform :ios do  
  desc "Push a new beta build to TestFlight"  
  lane :beta do  
    setup_ci if is_ci  
    
    app_store_connect_api_key(  
      key_id: ENV["APPLE_KEY_ID"],  
      issuer_id: ENV["APPLE_KEY_ISSUER_ID"],  
      key_content: ENV["APPLE_KEY_CONTENT"],  
      duration: 1200,  
      in_house: false  
    )  

    match(  
      type: "appstore",  
      readonly: is_ci,  
      git_url: ENV["MATCH_GIT_URL"],  
      password: ENV["MATCH_PASSWORD"]  
    )  

    increment_build_number(  
      build_number: latest_testflight_build_number + 1  
    )  

    build_app(  
      scheme: "hello-world-ios",  
      export_method: "app-store"  
    )  

    upload_to_testflight(  
      skip_waiting_for_build_processing: true  
    )  
  end  
end